pipeline {
    agent any
    
    environment {
        EC2_IP = "13.49.90.144"
    }
    
    stages {
        stage('checkout code') {
            steps {
               
                git branch: 'main',
                credentialsId: 'github-token-creds',
                url: 'https://github.com/greeshmagp19-creator/fullstack_project.git'
            }
        }
        
        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} << 'EOF'
                        set -e
                        mkdir -p /home/ubuntu/apps
                        cd /home/ubuntu/apps
                        
                       
                        if [ -d "fullstack_project" ] && [ ! -d "fullstack_project/.git" ]; then
                           rm -rf fullstack_project
                        fi
                        
                       
                        if [ ! -d "fullstack_project" ]; then
                           git clone https://github.com/greeshmagp19-creator/fullstack_project.git
                        fi
                        
                        cd fullstack_project
                        git fetch origin
                        git checkout main
                        git pull origin main
                       
                        cd backend
                      
                      
                        docker stop myapp || true
                        docker rm myapp || true
                        docker rmi backend-image || true

                        
                        docker build -t backend-image .
                        
                        
                        docker run -d -p 5001:5000 --name myapp \
                        -e MONGO_URI='mongodb+srv://greeshmagp19_db_user:RaMuitqtQ036vhmE@cluster0.rmxfatn.mongodb.net/guestbook?retryWrites=true&w=majority' \
                        backend-image
EOF
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo " DEPLOYMENT SUCCESSFUL"
        }
        failure {
            echo " DEPLOYMENT FAILED"
        }
    }
}